
matrix:
  cluster_id: null
  matrix_dir: null

# Simulation framework settings
max_concurrent_tasks: 100
rate_limit_enqueue: false

# Dispatcher settings
dispatcher:
  ray_resources:
    num_cpus: 1

debug: false
seed: 42
num_trial: 1

# Default output settings
output:
  path: "simulation_results.jsonl"
  success_only: False
