_target_: matrix.agents.dataset_loader.HuggingfaceDatasetLoader
name: "HuggingFaceH4/tau2-bench-data"
split: "train"
data_files: "domains/${domain}/tasks.json"
cut_off: null  # Set to number to limit dataset size
hub_download: True
